# This workflow will run unit tests

name: Run Unit Tests
on:
  push:
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      matrix:
        python-version: [ 3.6, 3.8 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/test_requirements.txt
          sudo apt install -y curl
          curl https://forslund.github.io/mycroft-desktop-repo/mycroft-desktop.gpg.key | sudo apt-key add - 2> /dev/null && echo "deb http://forslund.github.io/mycroft-desktop-repo bionic main" | sudo tee /etc/apt/sources.list.d/mycroft-desktop.list
          sudo apt-get update
          sudo apt install -y libsndfile1 mimic
      - name: Test Mimic TTS
        run: |
          pytest tests/test_mimic.py --junitxml=tests/tts-test-results.xml
      - name: Upload TTS test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results-3.6
          path: tests/tts-test-results.xml
        if: ${{ always() }}
